apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-net-http-hello-prqx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-net-http-hello-prqx
    app.kubernetes.io/part-of: go-net-http-hello
  name: go-net-http-hello-prqx
  namespace: samburrai-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: go-net-http-hello-prqx
status:
  loadBalancer: {}
